sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull susyknot/ci

env:
  - TEST=repo
  - TEST=upstream
  - TEST=scenario

script:
  - >
    docker run -it --rm --name ${TEST} \
        -e TRAVIS_REPO_SLUG \
        -e TRAVIS_PULL_REQUEST \
        -e TRAVIS_PULL_REQUEST_SLUG \
        -e TRAVIS_PULL_REQUEST_BRANCH \
        -e TRAVIS_BRANCH \
        -e TEST \
      susyknot/ci:latest run_tests
